### ISSUE TITLE
Interations with binary variables

### ISSUE THREAD

**Issue by victorn1** [ngreifer/cobalt#14]
I'd suggest that, for a binary variable, interactions be calculated for the both values of the variable, not just for 1 (for 0-1 variables). Let, say, we have a continuous variable _a_ and a binary variable _b_. Now only the distribution of _ab_ is assessed. It would be more correct to assess the both distributions: of _ab_ and _a(1-b)_.

**Comment by ngreifer** [comment]
Another great suggestion, and one that will be easy to implement.

**Comment by ngreifer** [comment]
Done!

**Comment by victorn1** [comment]
Thank you very much for your help! Waiting for CRAN package update.
