### ISSUE TITLE
Logical treatment indicator is not allowed

### ISSUE THREAD

**Issue by victorn1** [ngreifer/cobalt#16]
If I take a logical treatment indicator in the corresponding formula for bal.tab, I get the error:
Error: The argument to treat must be a vector of treatment statuses or the (quoted) name of a variable in data that contains treatment status.

Code to reproduce the problem:
```
n=20
a=as.logical(sample(2,n,replace=T)-1)
b=runif(n)
l=glm(a~b)
matched=sample(2,n,replace=T)-1
b1=bal.tab(as.integer(a)~b,weights=matched,method="matching",s.d.denom="pooled")
b2=bal.tab(a~b,weights=matched,method="matching",s.d.denom="pooled")
```
It would be convenient to have bal.tab() accepting logical values as well.

**Comment by ngreifer** [comment]
Good find, thank you. Fixed!
