### ISSUE TITLE
Issue installing on OSX 10.14.5

### ISSUE THREAD

**Issue by apbelz** [ngreifer/cobalt#27]
Hi:  I need help trying to install cobalt on my mac:  

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘grid’ 3.5.0 is already loaded, but >= 3.6.1 is required

I have just reinstalled Rstudio.  What is needed to resolve this namespace 'grid' issue? 

All help is appreciated!

**Comment by ngreifer** [comment]
You need the most updated version of R (version 3.6.1), which you can download from [CRAN](https://cran.r-project.org/). This was actually brought up by another user and you can download a fully-functional version of `cobalt` that doesn't have this issue using `devtools::install_github("ngreifer/cobalt")`. Let me know if this solves your issue.

**Comment by apbelz** [comment]
Arg, my bad.  I had updated Rstudio but not R.  Did not need your alternative version.  Thank you!
