### ISSUE TITLE
Density plot using bal.plot() from CBPS object

### ISSUE THREAD

**Issue by ariakhademi** [ngreifer/cobalt#31]
Thanks for providing the package cobalt. I'm trying to use it with the CBPS package, but I have a problem plotting. I can't get "bal.plot()" to generate density or histogram plots of the object generated by CBPS. Even if I specify the "type" and variable name properly, it returns a scatterplot. All of the examples provided online have tried objects generated by other packages such as MatchIt, but none with CBPS. However, other functions like love.plot() are working fine with CBPS. I was wondering if you've tried density plots for objects generated by CBPS?

**Comment by ngreifer** [comment]
H, thank you for bringing this up. Unfortunately I wasn't able to replicate this issue. Running the following always haves as expected:

``` r
library(CBPS); library(cobalt)
#> Loading required package: MASS
#> Loading required package: MatchIt
#> Loading required package: nnet
#> Loading required package: numDeriv
#> Loading required package: glmnet
#> Loading required package: Matrix
#> Loading required package: foreach
#> Loaded glmnet 2.0-18
#> CBPS: Covariate Balancing Propensity Score
#> Version: 0.21
#> Authors: Christian Fong [aut, cre],
#>   Marc Ratkovic [aut],
#>   Kosuke Imai [aut],
#>   Chad Hazlett [ctb],
#>   Xiaolin Yang [ctb],
#>   Sida Peng [ctb]
#>  cobalt (Version 3.9.0, Build Date: 2019-10-06 19:10:02 UTC)
#>    Please read the documentation at ?bal.tab to understand the default outputs.
#>    Submit bug reports and feature requests to https://github.com/ngreifer/cobalt/issues
#>    Install the development version (not guaranteed to be stable) with:
#>      devtools::install_github("ngreifer/cobalt")
#>    Thank you for using cobalt!
#> 
#> Attaching package: 'cobalt'
#> The following object is masked from 'package:MatchIt':
#> 
#>     lalonde
data("lalonde", package = "cobalt")

#Binary (0, 1) treatment
out <- CBPS(treat ~ age + educ + married + race, data = lalonde, ATT = 1)
#> [1] "Finding ATT with T=1 as the treatment.  Set ATT=2 to find ATT with T=0 as the treatment"
bal.plot(out, "age")
```

![](https://i.imgur.com/rzG1xC5.png)

``` r

out <- CBPS(treat ~ age + educ + married + race, data = lalonde, ATT = 0)
bal.plot(out, "age")
```

![](https://i.imgur.com/xuWNPcN.png)

``` r

#Factor treatment
out <- CBPS(race ~ age + educ + married + nodegree, data = lalonde)
bal.plot(out, "age")
```

![](https://i.imgur.com/9Xmf2pR.png)

``` r

#Binary (1, 2) treatment; CBPS treats as continuous,
#bal.plot correctly interprets as binary
lalonde$treat2 <- lalonde$treat + 1
out <- CBPS(treat2 ~ age + educ + married + race, data = lalonde, method = "exact")
#> Warning in CBPS.fit(X = structure(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, :
#> Treatment vector is numeric. Interpreting as a continuous treatment. To
#> solve for a binary or multi-valued treatment, make treat a factor.
bal.plot(out, "age")
```

![](https://i.imgur.com/R0I6fQQ.png)

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can you provide me with a reproducible example? Also, if this is causing you issues, you should try doing the same analysis using `WeightIt`, which performs CBPS too, using the same syntax.

**Comment by istallworthy** [comment]
I too seem to be having issues with bal.tab and other functions from cobalt accepting CBPS output (binary treatment). i keep getting "Error: 'f' must be a formula'. Any thoughts here? Thanks in advance for this package and any advice!

**Comment by ngreifer** [comment]
@istallworthy So sorry you're having this issue! Are you using the most recent version of `cobalt`? Can you tell me what other packages you have loaded when you run into this issue (this is almost certainly what the problem is)?

**Comment by istallworthy** [comment]
the code i'm using is as follows, in case this helps: 

form="INR_bin ~ BrestFed + BSI.6 + ESETA1.6 + HOMEETA1.6 + HomeOwnd + HrsOfTV + IBQDnovm + Infectin + KFastScr + Med_6_R + NC + NumHH2_R + PCX_NEG.6 + PCX_POS.6 + PEmply2 + PPJWHr2_R + PregOTC + RcvErlHS + RcvFodSt + RcvGvCC + RcvGvHC + RcvGvHou + RcvGvTrn + RcvSchFd + RcvWIC + RGotAFDC + RGotFodS + RGotPubH + RHasSO + RHealth + RMAge1st + RMarStat + RMomAgeU + SurpPreg + TcBlac2 + WghtLoss + WIND.6"

fit <- CBPS::CBPS(form, data=MSMDATA_temp, ATT=0, iterations = 1000,
                                standardize = TRUE, method = "exact", twostep = FALSE, 
                                sample.weights = NULL, baseline.formula = NULL,
                                diff.formula = NULL)
cobalt::bal.tab(fit)


Error: 'f' must be a formula.



I also tried again with the simplified

fit<-CBPS::CBPS(form,data=MSMDATA_temp)

and i get the same error.

thanks again!

**Comment by ngreifer** [comment]
I see. Could you try loading `cobalt` with `library()` instead of just using `::`? This is a problem I've had that I need to work on, but doing this can sometimes solve it.

**Comment by istallworthy** [comment]
i tried loading cobalt with library() before and after running CBPS and running just bal.tab() with :: but I'm still getting the same error. I do appreciate the ideas, though!

**Comment by ngreifer** [comment]
I just had a thought. Don't include quotes around your formula. It's unnecessary and is probably why `cobalt` doesn't think the formula is actually a formula. You should never supply formulas as a string and the fact that `CBPS` accepts this is a convenience for the user but leads to weird issues like this when formula inputs are required.

**Comment by istallworthy** [comment]
That worked, thank you! and thanks for the tip about forms. i really appreciate it and will be sure to change that. (side note: you are still correct in that it does require me to manually load the cobalt library and doesn't like when i use ::).

**Comment by ngreifer** [comment]
Glad that solved it, still concerned about `::` not working.

**Comment by istallworthy** [comment]
i don't know if this helps but this is the error i get when I remove the cobalt library and try to run cobalt::love.plot(fit):

Error in bal.tab(x = list(coefficients = c(0.882209404965283, -0.276814528516487,  : 
  could not find function "bal.tab"

The code runs if I pre-load the cobalt library manually.

**Comment by istallworthy** [comment]
i don't know if this helps but this is the error i get when I remove the cobalt library and try to run cobalt::love.plot(fit):

Error in bal.tab(x = list(coefficients = c(0.882209404965283, -0.276814528516487,  : 
  could not find function "bal.tab"

The code runs if I pre-load the cobalt library manually.

**Comment by ngreifer** [comment]
That is helpful! I just made an edit to the GitHub version to address this, I would really appreciate it if you could test it out for me. You can install it using
```
remotes::install_github("ngreifer/cobalt")
```
Thanks!

**Comment by istallworthy** [comment]
definitely! when i do that, i now get the following error when i try to run love.plot() after manually loading the library or cobalt::love.plot():

Error: (converted from warning) Unadjusted values are missing. This can occur when un = FALSE and quick = TRUE in the original call to bal.tab().
