### ISSUE TITLE
bal.tab not accepting numeric factor levels with mnps

### ISSUE THREAD

**Issue by KZARCA** [ngreifer/cobalt#35]
Hi,
from the twang example, if treat has character levels, it works:
```r
library(twang)
data(AOD)
mnps.AOD <- mnps(treat ~ illact + crimjust + subprob + subdep + white,
                 data = AOD, 
                 estimand = "ATE", 
                 verbose = FALSE, 
                 stop.method = c("es.mean"), 
                 n.trees = 3000)
bal.tab(mnps.AOD)
```
If, however, you add: `levels(AOD$treat) <- 1:3` at the beginning, you get 
```r
Error in `[.data.frame`(do.call("cbind", unname(lapply(bal.tab.multi.list,  : 
  undefined columns selected 
```

**Comment by ngreifer** [comment]
Thanks, someone else reported that bug and it’ll be fixed in the next release. If a multi-category treatment has names that are numbers, it won’t work. Use other names to make it work correctly for now.
