### ISSUE TITLE
bal.tab with mnps accepts only one stop.method

### ISSUE THREAD

**Issue by KZARCA** [ngreifer/cobalt#36]
From the twang example:

```r
library(twang)
data(AOD)
mnps.AOD <- mnps(treat ~ illact + crimjust + subprob + subdep + white,
                 data = AOD, 
                 estimand = "ATE", 
                 verbose = FALSE, 
                 stop.method = c("es.mean", "ks.mean"), 
                 n.trees = 3000)
bal.tab(mnps.AOD)
```

`Error in rep("all", length(errors) - 1) : argument 'times' incorrect`

**Comment by ngreifer** [comment]
Thank you for letting me know! I’ll look into this. 

By the way, when you say “the” twang example, where does this example appear? Or is it just an example you came up with?

**Comment by KZARCA** [comment]
Great! It is in the vignette named twang::mnps.

**Comment by ngreifer** [comment]
This has been fixed and will not cause an error in the updated version when it is released.
