### ISSUE TITLE
Add a cran badge to your readme

### ISSUE THREAD

**Issue by BarkleyBG** [ngreifer/cobalt#4]
If you type
```
    devtools::use_cran_badge()
```
then you should see some text about how to add a line to the top of your README document that adds a little badge for the CRAN version.

e.g.: https://github.com/bsaul/geex

**Comment by ngreifer** [comment]
Thank you!

**Comment by BarkleyBG** [comment]
You can keep the issue open until you've made the necessary changes. GitHub has a really nice feature that you can [auto-close issues with commits](https://github.com/blog/1386-closing-issues-via-commit-messages).

I'd recommend you keep this issue open until you've pushed the commit to github. In the commit message, you can write "fixes #4" (which is this issue), and once that commit makes it into the `master` branch, the issue with auto-close.
