### ISSUE TITLE
Incorrect {gridExtra} version number in DESCRIPTION file

### ISSUE THREAD

**Issue by bran-edwards** [ngreifer/cobalt#47]
### Problem
Under imports in the package DESCRIPTION file, gridExtra (>= 2.3.0) is listed

gridExtra 2.3.0 does not actually exist, 2.3 does.

### Consequences
`install.packges()` sees these as the same which is why this has gone unnoticed, however some package managers (yum, for example) do not, which causes issues on installation.

### Solution
replace `gridExtra (>= 2.3.0)` with `gridExtra (>= 2.3)` in the DESCRIPTION file.

**Comment by ngreifer** [comment]
Fixed! Thank you for pointing this out and sorry for the bug.
