### ISSUE TITLE
Select variables to include in the love plot

### ISSUE THREAD

**Issue by elsaallman** [ngreifer/cobalt#49]
I am trying to find a way of selecting the variables to display in the love.plot(). 

Following the example in the vignette on love plots, I was hoping to display only 3 variables: age, educ, and married. Is there any way to do that?

In practice, this is useful when including factor variables in the matching procedures (for example industries), and not wanting to display all these dummy variables in the love plot.

**Comment by ngreifer** [comment]
You can use the `data.frame` or `formula` methods. So, let's say you had a `matchit` object `m.out` where matching was done on variables other than the ones you want to display. You can run
```
love.plot(treat ~ age + educ + married, data = lalonde, weights = get.w(m.out))
```
You can then add customizations to the `love.plot()` call as usual. Let me know if this helps.

**Comment by elsaallman** [comment]
This works great, thank you Noah. This is a really great package.

**Comment by ngreifer** [comment]
Thank you for the kind words! Glad this was helpful.

**Comment by zaihra** [comment]
Thank you for pointing to this post, it worked!
