### ISSUE TITLE
Two rows of distance in bal.tab()$Balance when matching on a single binary variable

### ISSUE THREAD

**Issue by sky0502** [ngreifer/cobalt#57]
Hi, the balance table has two distance rows 
```
library(MatchIt)
library(cobalt)
data("lalonde")
m_out <- matchit(treat ~ married, data = lalonde, method = "nearest", distance = "glm")
m_summary <- bal.tab(m_out, un = TRUE)
m_summary$Balance
```
And output 
```
                               Type    Diff.Un Diff.Adj
distance_0.13725490196086  Distance -0.8240730        0
distance_0.417827298050138 Distance  0.8240730        0
married                      Binary -0.3236313        0
```
R version 4.1.0 (2021-05-18), cobalt_4.3.1,  MatchIt_4.2.0

**Comment by ngreifer-IQSS** [comment]
That is pretty strange. The reason for this is that because `distance` can only take on two values (i.e., based on whether `married=1` or `married=0`), `bal.tab()` treats it as a binary variable. I agree that this is undesired behavior, and I'll take a look. Thanks for pointing this out!
