### ISSUE TITLE
  On which statistical test are the p-values of the bal.tab function in the COBALT package in r based?

### ISSUE THREAD

**Issue by Monique2000** [ngreifer/cobalt#62]
I performed propensity score matching using the nearest neighbor method with the MatchIt-package. To assess the balance by matching I used the bal.tab function of the COBALT package setting the thresholds for mean differences to ".05".

`library(MatchIt)
m.outtest <- matchit(icu_mort ~ age + sex + duration_h,
                 data = testdata1,
                 method = "nearest", distance = "glm", replace = FALSE, ratio = 1, caliper = .2, std.caliper = FALSE)
bal.tab(m.outtest, continuous = "std", binary = "raw", disp = c("means"), un = TRUE, stats = c("m"),
        thresholds = c(m = .05))`

![image](https://user-images.githubusercontent.com/109208194/189839911-f54ab421-df1a-45ae-b618-2d335d492337.png)

I received a result about balance measure, but I did not find any information on which statistical tests the p-values are based on, which result in "balanced" or "not balanced".

Usually a p-value >0.05 means that there are no significant differences between the groups, but this is what is called "not balanced" here, that means there are differences between treatment group and control group after matching.

How to explain the (apparent) inconsistency regarding the meaning of the p-values?
On which statsitical tests are the p-values based?

**Comment by ngreifer** [comment]
There are no p-values in `cobalt`, see the [main vignette](https://ngreifer.github.io/cobalt/articles/cobalt.html#whats-missing-in-cobalt). The `M.Threshold` column indicates whether each mean difference is above or below the specified threshold. For `age`, the standardized mean difference is -.0307, which is less than .05 in absolute value, so the variable is balanced by that metric. For `duration_h`, the standardized mean difference is 1.056, which is greater than .05 in absolute value, so the variable is not balanced by that metric. This is described in the [documentation](https://ngreifer.github.io/cobalt/reference/bal.tab.html) for `bal.tab()`.

**Comment by Monique2000** [comment]
Thanks for clarifying my misunderstanding!
