### ISSUE TITLE
p-values?

### ISSUE THREAD

**Issue by aydindemircioglu** [ngreifer/cobalt#67]
this is possibly a stupid question, but since in bal.tab there are no p-values (see issue #62), is there a similarly easy function to compute those? i would actually also need these for other covariates, e.g., after matching for age, is there a difference in sex between the matched treatment groups. 

i am using svyglm for this right now, but am not quite happy; replacing $covs of the weightit result and calling bal.tab would have been much easier.

thanks for any hints! (and for the package!)

**Comment by ngreifer** [comment]
Don't compute p-values. There is a [section](https://ngreifer.github.io/cobalt/articles/cobalt.html#test-statistics-and-p-values) in the main vignette with citations that explain why. I'm not going to help you do something you shouldn't do. Please don't do it.

**Comment by aydindemircioglu** [comment]
thanks!-- i am very well aware of the situation, but i can argue as much as i want, medical sciences want p-values.  they dont even correct for family-wise errors... so ok, you point out the other packages, i will give them a try then. thanks again, and sorry about the p-values; it needs a more coordinated approach to get "rid" of these...
