### ISSUE TITLE
suggestions for using cobalt from within python?

### ISSUE THREAD

**Issue by ras44** [ngreifer/cobalt#73]
Thanks for building this very handy package.  I've used it extensively in R but recently have an application in which we need to interface from a python jupyter notebook using rpy2.  I've searched online, but can't find any obvious examples of generating balance plots or any other graphical features using cobalt from within jupyter.  I'm not sure if there's an easy way to export the image files, or render them directly within a jupyter notebook.

If you have any suggestions or references, I would greatly appreciate your help.

Thank you again!

**Comment by ngreifer** [comment]
Sorry, I don't know anything about how to use `rpy2` or jupyiter notebooks. The plots returned by `cobalt` functions are just regular `ggplot2` objects, so if you know how to handle those, the procedures should be the same. You can use `ggsave()` to save plots from R.

**Comment by ras44** [comment]
Thank you, that helped and I was able to get it to work.

Here's a quick example of using cobalt and matchit in a jupyter notebook:

Python:
```
import rpy2.ipython

%reload_ext rpy2.ipython

# import rpy2's package module
import rpy2.robjects.packages as rpackages
from rpy2.robjects.packages import importr, data
from rpy2.robjects import Formula


cobalt = rpackages.importr('cobalt')
matchit = rpackages.importr('MatchIt')

#data("lalonde", package = "cobalt")
lalonde = data(cobalt).fetch('lalonde')['lalonde']

formula = Formula('treat ~ age + educ + race + married + nodegree + re74 + re75')

mout = matchit.matchit(formula = formula, data=lalonde)

#Checking balance before and after matching:
bt = cobalt.bal_tab(mout, un = True) #, thresholds = c(m = .1),)
print(bt)
```

Output:
![image](https://github.com/ngreifer/cobalt/assets/9282281/4e53bb5d-6afd-462f-b312-fe7df2906ba5)




An R-"magic" cell to show the plots:
```
%%R -i mout
library("ggplot2", "cobalt", "MatchIt")
bal.plot(mout, var.name="educ")
```

Output:
![image](https://github.com/ngreifer/cobalt/assets/9282281/433aa9ba-1447-453c-8fd6-74dec53cc709)
