### ISSUE TITLE
Error in library(cobalt) : there is no package called ‘cobalt’

### ISSUE THREAD

**Issue by westmontashford** [ngreifer/cobalt#75]
i have installed and reinstalled multiple times, but i keep getting this issue when i try loading the cobalt library. help? thanks!

**Comment by ngreifer** [comment]
All I can say is you are probably typing something incorrectly. Show me every line of code you are using to try to install and run `cobalt`. I would bet there is a typo somewhere. Remember R is case-sensitive.

**Comment by westmontashford** [comment]
thanks for the response! turns out the issue was the version of R i had. i installed a newer version of R on a different computer and installed cobalt (the same way i had done the previous times) and this time around - on the newer version of R - it worked just fine. thanks again for the response!
