### ISSUE TITLE
How are the Diff.Adj calulated in bal.tab using a weighit object? 

### ISSUE THREAD

**Issue by norafino** [ngreifer/cobalt#81]
How are the Diff.Adj calulated in bal.tab using a weighit object?  I can't verify them using abs(mean_untreated - mean_untreated) / sd(treated)?

**Comment by ngreifer** [comment]
Did you read the documentation? This is described in many places (e.g., [here](https://ngreifer.github.io/cobalt/reference/bal.tab.html#with-binary-point-treatments)). Calculation depends on the covariate type (categorical/ binary vs. continuous) and the estimand. Please show your code, the output you get, and the output you expect to get.

**Comment by norafino** [comment]
yes - I understand they differ by covariate type and estimand, but when I try to calculate them by hand based on what I read in the documentation, I get different results 

for example, see screenshot. What do you use in the denominator? 
![image](https://github.com/ngreifer/cobalt/assets/77459687/c7325079-448c-473b-8322-37103c273a03)

**Comment by ngreifer** [comment]
Well, by default `weightit()` targets the ATE, so we would have the pooled SD in the denominator, not the standard deviation of the treated. As explained in the documentation in the [link](https://ngreifer.github.io/cobalt/reference/bal.tab.html#with-binary-point-treatments) I included above, I say

> The computed spread bal.tab() uses is always that of the full, unadjusted sample (i.e., before matching, weighting, or subclassification), as recommended by Stuart (2010).

I also describe this [here](https://ngreifer.github.io/cobalt/articles/cobalt.html#variance-in-standardized-mean-differences-and-correlations):

> A key detail is that the standard deviation, no matter how it is computed, is always computed using the _unadjusted_ sample

You computed the pooled SD using the weighted standard deviations. You can view the unweighted SDs by setting `un = TRUE` in `bal.tab()`.

**Comment by norafino** [comment]
got it - thanks!
