### ISSUE TITLE
Unadjusted differences in bal.tab are all NA

### ISSUE THREAD

**Issue by ajinkya-k** [ngreifer/cobalt#87]
Hello! 

I am using `cobalt::bal.tab` with a `data.frame` as the `x` object. While the `Diff.Adj` column in `Balance` is correct, the `Diff.Un` column is full of `NA`. 

I am using the following code: 

```
btt <- bal.tab(
  dt_x, # contains the covariates and the treatment in column trt, weights in column `wts`
    treat = "art",
  data = dt_x,
  weights = "wts",
  s.d.denom = "pooled",
)
```

**Comment by ngreifer** [comment]
If you set `un = TRUE` or `quick = FALSE`, unadjusted statistics will be computed. They are not computed otherwise to save processing time and avoid computing unnecessary information.
